# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v1
    - name: Restore local Maven cache
      uses: actions/cache@v2.1.0
      with:
        path: ~/.m2
        key: m2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Codecov
      uses: codecov/codecov-action@v1.0.12
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Set branch name and PR number
      id: refs
      env:
        BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
      run: |
        echo "::set-output name=branch_name::${BRANCH_NAME_OR_REF#refs/heads/}"
        echo "::set-output name=pr_number::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
    - name: Coveralls Maven plugin
      env:
        CI_NAME: Github
        CI_BUILD_NUMBER: ${{ github.run_id }}
        CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
        CI_BRANCH: ${{ steps.refs.outputs.branch_name }}
        CI_PULL_REQUEST: ${{ steps.refs.outputs.pr_number }}
      run: |
        mvn coveralls:report \
        --no-transfer-progress \
        -D repoToken=${{ secrets.COVERALLS_TOKEN }}
#        -D serviceName=Github \
#        -D serviceBuildUrl=https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks \
#        -D branch=${{ steps.refs.outputs.branch_name }} \
#        -D pullRequest=${{ steps.refs.outputs.pr_number }}
    - name: Code Climate
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        JACOCO_SOURCE_PATH: "${{ github.workspace }}/pravega-cdi/src/main/java"
      with:
        coverageCommand: "true"
        coverageLocations: ${{ github.workspace }}/pravega-cdi/target/site/jacoco/jacoco.xml:jacoco
